/**
 * Autogenerated by Thrift Compiler (0.12.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#include "ApiServidor_constants.h"

namespace Thrift {

const ApiServidorConstants g_ApiServidor_constants;

ApiServidorConstants::ApiServidorConstants() {
}

} // namespace

