/**
 * Autogenerated by Thrift Compiler (0.12.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
package Thrift;

@SuppressWarnings({"cast", "rawtypes", "serial", "unchecked", "unused"})
@javax.annotation.Generated(value = "Autogenerated by Thrift Compiler (0.12.0)", date = "2019-06-28")
public class VehiculosReporte implements org.apache.thrift.TBase<VehiculosReporte, VehiculosReporte._Fields>, java.io.Serializable, Cloneable, Comparable<VehiculosReporte> {
  private static final org.apache.thrift.protocol.TStruct STRUCT_DESC = new org.apache.thrift.protocol.TStruct("VehiculosReporte");

  private static final org.apache.thrift.protocol.TField PLACA_VEHICULO1_FIELD_DESC = new org.apache.thrift.protocol.TField("placaVehiculo1", org.apache.thrift.protocol.TType.STRING, (short)1);
  private static final org.apache.thrift.protocol.TField PLACA_VEHICULO2_FIELD_DESC = new org.apache.thrift.protocol.TField("placaVehiculo2", org.apache.thrift.protocol.TType.STRING, (short)2);

  private static final org.apache.thrift.scheme.SchemeFactory STANDARD_SCHEME_FACTORY = new VehiculosReporteStandardSchemeFactory();
  private static final org.apache.thrift.scheme.SchemeFactory TUPLE_SCHEME_FACTORY = new VehiculosReporteTupleSchemeFactory();

  public @org.apache.thrift.annotation.Nullable java.lang.String placaVehiculo1; // required
  public @org.apache.thrift.annotation.Nullable java.lang.String placaVehiculo2; // required

  /** The set of fields this struct contains, along with convenience methods for finding and manipulating them. */
  public enum _Fields implements org.apache.thrift.TFieldIdEnum {
    PLACA_VEHICULO1((short)1, "placaVehiculo1"),
    PLACA_VEHICULO2((short)2, "placaVehiculo2");

    private static final java.util.Map<java.lang.String, _Fields> byName = new java.util.HashMap<java.lang.String, _Fields>();

    static {
      for (_Fields field : java.util.EnumSet.allOf(_Fields.class)) {
        byName.put(field.getFieldName(), field);
      }
    }

    /**
     * Find the _Fields constant that matches fieldId, or null if its not found.
     */
    @org.apache.thrift.annotation.Nullable
    public static _Fields findByThriftId(int fieldId) {
      switch(fieldId) {
        case 1: // PLACA_VEHICULO1
          return PLACA_VEHICULO1;
        case 2: // PLACA_VEHICULO2
          return PLACA_VEHICULO2;
        default:
          return null;
      }
    }

    /**
     * Find the _Fields constant that matches fieldId, throwing an exception
     * if it is not found.
     */
    public static _Fields findByThriftIdOrThrow(int fieldId) {
      _Fields fields = findByThriftId(fieldId);
      if (fields == null) throw new java.lang.IllegalArgumentException("Field " + fieldId + " doesn't exist!");
      return fields;
    }

    /**
     * Find the _Fields constant that matches name, or null if its not found.
     */
    @org.apache.thrift.annotation.Nullable
    public static _Fields findByName(java.lang.String name) {
      return byName.get(name);
    }

    private final short _thriftId;
    private final java.lang.String _fieldName;

    _Fields(short thriftId, java.lang.String fieldName) {
      _thriftId = thriftId;
      _fieldName = fieldName;
    }

    public short getThriftFieldId() {
      return _thriftId;
    }

    public java.lang.String getFieldName() {
      return _fieldName;
    }
  }

  // isset id assignments
  public static final java.util.Map<_Fields, org.apache.thrift.meta_data.FieldMetaData> metaDataMap;
  static {
    java.util.Map<_Fields, org.apache.thrift.meta_data.FieldMetaData> tmpMap = new java.util.EnumMap<_Fields, org.apache.thrift.meta_data.FieldMetaData>(_Fields.class);
    tmpMap.put(_Fields.PLACA_VEHICULO1, new org.apache.thrift.meta_data.FieldMetaData("placaVehiculo1", org.apache.thrift.TFieldRequirementType.DEFAULT, 
        new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.STRING)));
    tmpMap.put(_Fields.PLACA_VEHICULO2, new org.apache.thrift.meta_data.FieldMetaData("placaVehiculo2", org.apache.thrift.TFieldRequirementType.DEFAULT, 
        new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.STRING)));
    metaDataMap = java.util.Collections.unmodifiableMap(tmpMap);
    org.apache.thrift.meta_data.FieldMetaData.addStructMetaDataMap(VehiculosReporte.class, metaDataMap);
  }

  public VehiculosReporte() {
  }

  public VehiculosReporte(
    java.lang.String placaVehiculo1,
    java.lang.String placaVehiculo2)
  {
    this();
    this.placaVehiculo1 = placaVehiculo1;
    this.placaVehiculo2 = placaVehiculo2;
  }

  /**
   * Performs a deep copy on <i>other</i>.
   */
  public VehiculosReporte(VehiculosReporte other) {
    if (other.isSetPlacaVehiculo1()) {
      this.placaVehiculo1 = other.placaVehiculo1;
    }
    if (other.isSetPlacaVehiculo2()) {
      this.placaVehiculo2 = other.placaVehiculo2;
    }
  }

  public VehiculosReporte deepCopy() {
    return new VehiculosReporte(this);
  }

  @Override
  public void clear() {
    this.placaVehiculo1 = null;
    this.placaVehiculo2 = null;
  }

  @org.apache.thrift.annotation.Nullable
  public java.lang.String getPlacaVehiculo1() {
    return this.placaVehiculo1;
  }

  public VehiculosReporte setPlacaVehiculo1(@org.apache.thrift.annotation.Nullable java.lang.String placaVehiculo1) {
    this.placaVehiculo1 = placaVehiculo1;
    return this;
  }

  public void unsetPlacaVehiculo1() {
    this.placaVehiculo1 = null;
  }

  /** Returns true if field placaVehiculo1 is set (has been assigned a value) and false otherwise */
  public boolean isSetPlacaVehiculo1() {
    return this.placaVehiculo1 != null;
  }

  public void setPlacaVehiculo1IsSet(boolean value) {
    if (!value) {
      this.placaVehiculo1 = null;
    }
  }

  @org.apache.thrift.annotation.Nullable
  public java.lang.String getPlacaVehiculo2() {
    return this.placaVehiculo2;
  }

  public VehiculosReporte setPlacaVehiculo2(@org.apache.thrift.annotation.Nullable java.lang.String placaVehiculo2) {
    this.placaVehiculo2 = placaVehiculo2;
    return this;
  }

  public void unsetPlacaVehiculo2() {
    this.placaVehiculo2 = null;
  }

  /** Returns true if field placaVehiculo2 is set (has been assigned a value) and false otherwise */
  public boolean isSetPlacaVehiculo2() {
    return this.placaVehiculo2 != null;
  }

  public void setPlacaVehiculo2IsSet(boolean value) {
    if (!value) {
      this.placaVehiculo2 = null;
    }
  }

  public void setFieldValue(_Fields field, @org.apache.thrift.annotation.Nullable java.lang.Object value) {
    switch (field) {
    case PLACA_VEHICULO1:
      if (value == null) {
        unsetPlacaVehiculo1();
      } else {
        setPlacaVehiculo1((java.lang.String)value);
      }
      break;

    case PLACA_VEHICULO2:
      if (value == null) {
        unsetPlacaVehiculo2();
      } else {
        setPlacaVehiculo2((java.lang.String)value);
      }
      break;

    }
  }

  @org.apache.thrift.annotation.Nullable
  public java.lang.Object getFieldValue(_Fields field) {
    switch (field) {
    case PLACA_VEHICULO1:
      return getPlacaVehiculo1();

    case PLACA_VEHICULO2:
      return getPlacaVehiculo2();

    }
    throw new java.lang.IllegalStateException();
  }

  /** Returns true if field corresponding to fieldID is set (has been assigned a value) and false otherwise */
  public boolean isSet(_Fields field) {
    if (field == null) {
      throw new java.lang.IllegalArgumentException();
    }

    switch (field) {
    case PLACA_VEHICULO1:
      return isSetPlacaVehiculo1();
    case PLACA_VEHICULO2:
      return isSetPlacaVehiculo2();
    }
    throw new java.lang.IllegalStateException();
  }

  @Override
  public boolean equals(java.lang.Object that) {
    if (that == null)
      return false;
    if (that instanceof VehiculosReporte)
      return this.equals((VehiculosReporte)that);
    return false;
  }

  public boolean equals(VehiculosReporte that) {
    if (that == null)
      return false;
    if (this == that)
      return true;

    boolean this_present_placaVehiculo1 = true && this.isSetPlacaVehiculo1();
    boolean that_present_placaVehiculo1 = true && that.isSetPlacaVehiculo1();
    if (this_present_placaVehiculo1 || that_present_placaVehiculo1) {
      if (!(this_present_placaVehiculo1 && that_present_placaVehiculo1))
        return false;
      if (!this.placaVehiculo1.equals(that.placaVehiculo1))
        return false;
    }

    boolean this_present_placaVehiculo2 = true && this.isSetPlacaVehiculo2();
    boolean that_present_placaVehiculo2 = true && that.isSetPlacaVehiculo2();
    if (this_present_placaVehiculo2 || that_present_placaVehiculo2) {
      if (!(this_present_placaVehiculo2 && that_present_placaVehiculo2))
        return false;
      if (!this.placaVehiculo2.equals(that.placaVehiculo2))
        return false;
    }

    return true;
  }

  @Override
  public int hashCode() {
    int hashCode = 1;

    hashCode = hashCode * 8191 + ((isSetPlacaVehiculo1()) ? 131071 : 524287);
    if (isSetPlacaVehiculo1())
      hashCode = hashCode * 8191 + placaVehiculo1.hashCode();

    hashCode = hashCode * 8191 + ((isSetPlacaVehiculo2()) ? 131071 : 524287);
    if (isSetPlacaVehiculo2())
      hashCode = hashCode * 8191 + placaVehiculo2.hashCode();

    return hashCode;
  }

  @Override
  public int compareTo(VehiculosReporte other) {
    if (!getClass().equals(other.getClass())) {
      return getClass().getName().compareTo(other.getClass().getName());
    }

    int lastComparison = 0;

    lastComparison = java.lang.Boolean.valueOf(isSetPlacaVehiculo1()).compareTo(other.isSetPlacaVehiculo1());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetPlacaVehiculo1()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.placaVehiculo1, other.placaVehiculo1);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = java.lang.Boolean.valueOf(isSetPlacaVehiculo2()).compareTo(other.isSetPlacaVehiculo2());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetPlacaVehiculo2()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.placaVehiculo2, other.placaVehiculo2);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    return 0;
  }

  @org.apache.thrift.annotation.Nullable
  public _Fields fieldForId(int fieldId) {
    return _Fields.findByThriftId(fieldId);
  }

  public void read(org.apache.thrift.protocol.TProtocol iprot) throws org.apache.thrift.TException {
    scheme(iprot).read(iprot, this);
  }

  public void write(org.apache.thrift.protocol.TProtocol oprot) throws org.apache.thrift.TException {
    scheme(oprot).write(oprot, this);
  }

  @Override
  public java.lang.String toString() {
    java.lang.StringBuilder sb = new java.lang.StringBuilder("VehiculosReporte(");
    boolean first = true;

    sb.append("placaVehiculo1:");
    if (this.placaVehiculo1 == null) {
      sb.append("null");
    } else {
      sb.append(this.placaVehiculo1);
    }
    first = false;
    if (!first) sb.append(", ");
    sb.append("placaVehiculo2:");
    if (this.placaVehiculo2 == null) {
      sb.append("null");
    } else {
      sb.append(this.placaVehiculo2);
    }
    first = false;
    sb.append(")");
    return sb.toString();
  }

  public void validate() throws org.apache.thrift.TException {
    // check for required fields
    // check for sub-struct validity
  }

  private void writeObject(java.io.ObjectOutputStream out) throws java.io.IOException {
    try {
      write(new org.apache.thrift.protocol.TCompactProtocol(new org.apache.thrift.transport.TIOStreamTransport(out)));
    } catch (org.apache.thrift.TException te) {
      throw new java.io.IOException(te);
    }
  }

  private void readObject(java.io.ObjectInputStream in) throws java.io.IOException, java.lang.ClassNotFoundException {
    try {
      read(new org.apache.thrift.protocol.TCompactProtocol(new org.apache.thrift.transport.TIOStreamTransport(in)));
    } catch (org.apache.thrift.TException te) {
      throw new java.io.IOException(te);
    }
  }

  private static class VehiculosReporteStandardSchemeFactory implements org.apache.thrift.scheme.SchemeFactory {
    public VehiculosReporteStandardScheme getScheme() {
      return new VehiculosReporteStandardScheme();
    }
  }

  private static class VehiculosReporteStandardScheme extends org.apache.thrift.scheme.StandardScheme<VehiculosReporte> {

    public void read(org.apache.thrift.protocol.TProtocol iprot, VehiculosReporte struct) throws org.apache.thrift.TException {
      org.apache.thrift.protocol.TField schemeField;
      iprot.readStructBegin();
      while (true)
      {
        schemeField = iprot.readFieldBegin();
        if (schemeField.type == org.apache.thrift.protocol.TType.STOP) { 
          break;
        }
        switch (schemeField.id) {
          case 1: // PLACA_VEHICULO1
            if (schemeField.type == org.apache.thrift.protocol.TType.STRING) {
              struct.placaVehiculo1 = iprot.readString();
              struct.setPlacaVehiculo1IsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          case 2: // PLACA_VEHICULO2
            if (schemeField.type == org.apache.thrift.protocol.TType.STRING) {
              struct.placaVehiculo2 = iprot.readString();
              struct.setPlacaVehiculo2IsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          default:
            org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
        }
        iprot.readFieldEnd();
      }
      iprot.readStructEnd();

      // check for required fields of primitive type, which can't be checked in the validate method
      struct.validate();
    }

    public void write(org.apache.thrift.protocol.TProtocol oprot, VehiculosReporte struct) throws org.apache.thrift.TException {
      struct.validate();

      oprot.writeStructBegin(STRUCT_DESC);
      if (struct.placaVehiculo1 != null) {
        oprot.writeFieldBegin(PLACA_VEHICULO1_FIELD_DESC);
        oprot.writeString(struct.placaVehiculo1);
        oprot.writeFieldEnd();
      }
      if (struct.placaVehiculo2 != null) {
        oprot.writeFieldBegin(PLACA_VEHICULO2_FIELD_DESC);
        oprot.writeString(struct.placaVehiculo2);
        oprot.writeFieldEnd();
      }
      oprot.writeFieldStop();
      oprot.writeStructEnd();
    }

  }

  private static class VehiculosReporteTupleSchemeFactory implements org.apache.thrift.scheme.SchemeFactory {
    public VehiculosReporteTupleScheme getScheme() {
      return new VehiculosReporteTupleScheme();
    }
  }

  private static class VehiculosReporteTupleScheme extends org.apache.thrift.scheme.TupleScheme<VehiculosReporte> {

    @Override
    public void write(org.apache.thrift.protocol.TProtocol prot, VehiculosReporte struct) throws org.apache.thrift.TException {
      org.apache.thrift.protocol.TTupleProtocol oprot = (org.apache.thrift.protocol.TTupleProtocol) prot;
      java.util.BitSet optionals = new java.util.BitSet();
      if (struct.isSetPlacaVehiculo1()) {
        optionals.set(0);
      }
      if (struct.isSetPlacaVehiculo2()) {
        optionals.set(1);
      }
      oprot.writeBitSet(optionals, 2);
      if (struct.isSetPlacaVehiculo1()) {
        oprot.writeString(struct.placaVehiculo1);
      }
      if (struct.isSetPlacaVehiculo2()) {
        oprot.writeString(struct.placaVehiculo2);
      }
    }

    @Override
    public void read(org.apache.thrift.protocol.TProtocol prot, VehiculosReporte struct) throws org.apache.thrift.TException {
      org.apache.thrift.protocol.TTupleProtocol iprot = (org.apache.thrift.protocol.TTupleProtocol) prot;
      java.util.BitSet incoming = iprot.readBitSet(2);
      if (incoming.get(0)) {
        struct.placaVehiculo1 = iprot.readString();
        struct.setPlacaVehiculo1IsSet(true);
      }
      if (incoming.get(1)) {
        struct.placaVehiculo2 = iprot.readString();
        struct.setPlacaVehiculo2IsSet(true);
      }
    }
  }

  private static <S extends org.apache.thrift.scheme.IScheme> S scheme(org.apache.thrift.protocol.TProtocol proto) {
    return (org.apache.thrift.scheme.StandardScheme.class.equals(proto.getScheme()) ? STANDARD_SCHEME_FACTORY : TUPLE_SCHEME_FACTORY).getScheme();
  }
}

