/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vistas.Perito;


import Thrift.Conexiones;
import Thrift.Dictamen;
import Thrift.ErrorBD;
import Thrift.Reporte;
import Vistas.Todos.IniciarSesion;
import java.awt.Image;
import java.awt.event.KeyEvent;
import java.util.ArrayList;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import org.apache.thrift.TException;


/**
 *
 * @author cris_
 */
public class ConsultarReporte extends javax.swing.JFrame {

    /**
     * Creates new form InicioPerito
     */
    Conexiones conexiones;
    String nombre, usuario, contrasena, estatusDictamen = null;
    Integer idReporte;
    ArrayList<ImageIcon> listaImagenes;
    int posicion = 0;

    private void actualizarMenu() {
        String primerNombre = this.nombre.split(" ")[0].trim();
        menuBienvenido.setText("BIENVENIDO: " + primerNombre);
        conexiones = new Conexiones();
    }

    private void cerrarSesion() {
        IniciarSesion inicio = new IniciarSesion();
        inicio.setVisible(true);
        this.dispose();

    }

    public ConsultarReporte(String nombre, String usuario, String contrasena, String estatusDictamen, Integer idReporte) {
        initComponents();
        this.nombre = nombre;
        this.usuario = usuario;
        this.contrasena = contrasena;
        this.estatusDictamen = estatusDictamen;
        this.idReporte = idReporte;
        if ("CERRADO".equals(estatusDictamen)) {
            btnLevantarDictamen.setVisible(false);

        } else {
            txtDictamen.setEnabled(true);
            lblFechaDictamen.setVisible(false);
            lblDeFecha.setVisible(false);
        }
        listaImagenes = new ArrayList<>();
        actualizarMenu();
        llenarDatos();
        cargarImagenes();
    }
    
    private void cargarImagenes(){
       
        ImageIcon imagen = new ImageIcon(getClass().getResource("/Imagenes/choque1.jpg"));
        ImageIcon imagen2 = new ImageIcon(getClass().getResource("/Imagenes/choque2.jpg"));
        listaImagenes.add(imagen);
        listaImagenes.add(imagen2);
        Icon icono = new ImageIcon(imagen.getImage().getScaledInstance(lblImagen.getWidth(), lblImagen.getHeight(),Image.SCALE_DEFAULT)); 
        lblImagen.setIcon(icono);   
        
    }
    
    

    private void llenarDatos() {
        try {
                                  
            Reporte reporte = conexiones.getReporte(idReporte);
            txtLatitud.setText(reporte.getLatitud());
            txtLongitud.setText(reporte.getLongitud());
            txtOtroConductor.setText(reporte.getNombreOtroConduc());
            lblConductor.setText("CONDUCTOR: " + reporte.getNombreConductor());
            if (reporte.getDictamen() == 0) {
                txtEstatusDictamen.setText("ABIERTO");
            } else {
                txtEstatusDictamen.setText("CERRADO");
                Dictamen dictamen = conexiones.getDictamen(idReporte);
                txtDictamen.setText(dictamen.getDictamen());
                lblFechaDictamen.setText(dictamen.getFecha());
            }

        } catch (ErrorBD error) {
            System.out.println("ERROR: " + error.codigoError + " " + error.problema);
            JOptionPane.showConfirmDialog(null, "Datos no diponibles, intente más tarde", "Problema de conexión", JOptionPane.DEFAULT_OPTION, JOptionPane.WARNING_MESSAGE);
        } catch (TException ex) {
            conexiones.abrirConexion();
            conexiones.cerrarConexion();
            JOptionPane.showConfirmDialog(null, "Error de conexión con el servidor", "Problema de conexión", JOptionPane.DEFAULT_OPTION, JOptionPane.WARNING_MESSAGE);
        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel3 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        btnLevantarDictamen = new javax.swing.JButton();
        lblConductor = new javax.swing.JLabel();
        txtLatitud = new javax.swing.JTextField();
        lblLongitud = new javax.swing.JLabel();
        txtLongitud = new javax.swing.JTextField();
        lblOtroConductor = new javax.swing.JLabel();
        lblDictamen = new javax.swing.JLabel();
        lblLatitud = new javax.swing.JLabel();
        txtEstatusDictamen = new javax.swing.JTextField();
        txtOtroConductor = new javax.swing.JTextField();
        lblFechaDictamen = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtDictamen = new javax.swing.JTextArea();
        lblEstatusDictamen1 = new javax.swing.JLabel();
        lblDeFecha = new javax.swing.JLabel();
        btnAtras = new javax.swing.JButton();
        lblTitulo = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        lblImagen = new javax.swing.JLabel();
        btnSigImagen = new javax.swing.JButton();
        btnAntImagen = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        menuBienvenido = new javax.swing.JMenu();
        menuCerrarSesion = new javax.swing.JMenuItem();

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Registrar Nuevo Perito");
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setLayout(null);

        btnLevantarDictamen.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnLevantarDictamen.setText("LEVANTAR DICTAMEN");
        btnLevantarDictamen.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btnLevantarDictamen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLevantarDictamenActionPerformed(evt);
            }
        });
        btnLevantarDictamen.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                btnLevantarDictamenKeyPressed(evt);
            }
        });
        jPanel2.add(btnLevantarDictamen);
        btnLevantarDictamen.setBounds(320, 360, 200, 40);

        lblConductor.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblConductor.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblConductor.setText("CONDUCTOR: ");
        jPanel2.add(lblConductor);
        lblConductor.setBounds(30, 0, 490, 40);

        txtLatitud.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtLatitud.setToolTipText("");
        txtLatitud.setEnabled(false);
        txtLatitud.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtLatitudActionPerformed(evt);
            }
        });
        jPanel2.add(txtLatitud);
        txtLatitud.setBounds(90, 60, 180, 40);

        lblLongitud.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblLongitud.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblLongitud.setText("Longitud");
        jPanel2.add(lblLongitud);
        lblLongitud.setBounds(280, 60, 60, 40);

        txtLongitud.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtLongitud.setToolTipText("");
        txtLongitud.setEnabled(false);
        txtLongitud.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtLongitudActionPerformed(evt);
            }
        });
        jPanel2.add(txtLongitud);
        txtLongitud.setBounds(350, 60, 180, 40);

        lblOtroConductor.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblOtroConductor.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblOtroConductor.setText("Otro Conductor");
        jPanel2.add(lblOtroConductor);
        lblOtroConductor.setBounds(20, 120, 120, 40);

        lblDictamen.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblDictamen.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblDictamen.setText("Dictamen");
        jPanel2.add(lblDictamen);
        lblDictamen.setBounds(40, 220, 100, 40);

        lblLatitud.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblLatitud.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblLatitud.setText("Latitud");
        jPanel2.add(lblLatitud);
        lblLatitud.setBounds(20, 60, 50, 40);

        txtEstatusDictamen.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtEstatusDictamen.setToolTipText("");
        txtEstatusDictamen.setEnabled(false);
        txtEstatusDictamen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtEstatusDictamenActionPerformed(evt);
            }
        });
        jPanel2.add(txtEstatusDictamen);
        txtEstatusDictamen.setBounds(150, 170, 380, 40);

        txtOtroConductor.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtOtroConductor.setToolTipText("");
        txtOtroConductor.setEnabled(false);
        txtOtroConductor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtOtroConductorActionPerformed(evt);
            }
        });
        jPanel2.add(txtOtroConductor);
        txtOtroConductor.setBounds(150, 120, 380, 40);

        lblFechaDictamen.setFont(new java.awt.Font("Tahoma", 2, 14)); // NOI18N
        lblFechaDictamen.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblFechaDictamen.setText("Fecha Dictamen:  ");
        jPanel2.add(lblFechaDictamen);
        lblFechaDictamen.setBounds(230, 320, 300, 40);

        txtDictamen.setColumns(20);
        txtDictamen.setRows(5);
        txtDictamen.setEnabled(false);
        txtDictamen.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtDictamenKeyTyped(evt);
            }
        });
        jScrollPane1.setViewportView(txtDictamen);

        jPanel2.add(jScrollPane1);
        jScrollPane1.setBounds(150, 220, 380, 96);

        lblEstatusDictamen1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblEstatusDictamen1.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblEstatusDictamen1.setText("Estatus Dictamen");
        jPanel2.add(lblEstatusDictamen1);
        lblEstatusDictamen1.setBounds(20, 170, 120, 40);

        lblDeFecha.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblDeFecha.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblDeFecha.setText("Fecha Dictamen:");
        jPanel2.add(lblDeFecha);
        lblDeFecha.setBounds(70, 320, 150, 40);

        btnAtras.setBackground(new java.awt.Color(255, 255, 255));
        btnAtras.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/back-arrow 24.png"))); // NOI18N
        btnAtras.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAtrasActionPerformed(evt);
            }
        });
        btnAtras.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                btnAtrasKeyPressed(evt);
            }
        });

        lblTitulo.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        lblTitulo.setText("CONSULTAR REPORTE");

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));

        lblImagen.setBackground(new java.awt.Color(255, 255, 255));

        btnSigImagen.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnSigImagen.setText(">");
        btnSigImagen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSigImagenActionPerformed(evt);
            }
        });

        btnAntImagen.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnAntImagen.setText("<");
        btnAntImagen.setEnabled(false);
        btnAntImagen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAntImagenActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblImagen, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap(220, Short.MAX_VALUE)
                .addComponent(btnSigImagen, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(67, 67, 67))
            .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel4Layout.createSequentialGroup()
                    .addGap(55, 55, 55)
                    .addComponent(btnAntImagen, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(232, Short.MAX_VALUE)))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(lblImagen, javax.swing.GroupLayout.PREFERRED_SIZE, 257, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27)
                .addComponent(btnSigImagen, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(26, Short.MAX_VALUE))
            .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                    .addContainerGap(311, Short.MAX_VALUE)
                    .addComponent(btnAntImagen, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(25, 25, 25)))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(36, 36, 36)
                        .addComponent(btnAtras)
                        .addGap(206, 206, 206)
                        .addComponent(lblTitulo))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 546, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(22, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnAtras, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblTitulo))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, 434, Short.MAX_VALUE)
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(43, 43, 43))))
        );

        menuBienvenido.setText("BIENVENIDO JUAN");
        menuBienvenido.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N

        menuCerrarSesion.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/exit.png"))); // NOI18N
        menuCerrarSesion.setText("CERRAR SESIÓN");
        menuCerrarSesion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuCerrarSesionActionPerformed(evt);
            }
        });
        menuBienvenido.add(menuCerrarSesion);

        jMenuBar1.add(menuBienvenido);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void menuCerrarSesionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuCerrarSesionActionPerformed
        int confirmacion = JOptionPane.showConfirmDialog(null, "¿Desea cerrar la sesión actual?", "Cerrar Sesión",
                JOptionPane.YES_NO_OPTION, JOptionPane.INFORMATION_MESSAGE);
        if (confirmacion == 0) {
            cerrarSesion();
        }
    }//GEN-LAST:event_menuCerrarSesionActionPerformed

    private void btnLevantarDictamenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLevantarDictamenActionPerformed
        if (!txtDictamen.getText().isEmpty()) {
            int confirmacion = JOptionPane.showConfirmDialog(null, "Confirmar registro del dictamen", "Confirmar Registro",
                    JOptionPane.YES_NO_OPTION, JOptionPane.INFORMATION_MESSAGE);
            if (confirmacion == 0) {
                Dictamen dictamen = new Dictamen();
               // java.util.Date dt = new java.util.Date();
                //java.text.SimpleDateFormat sdf = new java.text.SimpleDateFormat("yyyy-MM-dd HH:mm:ss");
                //dictamen.setFecha(sdf.format(dt));
                try {
                    dictamen.setIdfuncionario(conexiones.getIdPerito(this.usuario));
                    dictamen.setIdreporte(idReporte);
                    dictamen.setDictamen(txtDictamen.getText());
                    if (conexiones.levantarDictamen(dictamen)) {
                        JOptionPane.showConfirmDialog(null, "Dictamen levantado exitosamente", "Registro exitoso", JOptionPane.DEFAULT_OPTION, JOptionPane.INFORMATION_MESSAGE);
                        ConsultarReporte consultarReporte = new ConsultarReporte(nombre, usuario, contrasena, "CERRADO", idReporte);
                        consultarReporte.setVisible(true);
                        this.dispose();
                    } else {
                        JOptionPane.showConfirmDialog(null, "Ya existe un dictamen o hubo un error al realizar el registro", "Error al guardar", JOptionPane.DEFAULT_OPTION, JOptionPane.INFORMATION_MESSAGE);
                    }

                } catch (ErrorBD error) {
                    System.out.println("ERROR: " + error.codigoError + " " + error.problema);
                    JOptionPane.showConfirmDialog(null, "Datos no diponibles, intente más tarde", "Problema de conexión", JOptionPane.DEFAULT_OPTION, JOptionPane.WARNING_MESSAGE);
                } catch (TException ex) {
                    conexiones.abrirConexion();
                    conexiones.cerrarConexion();
                    JOptionPane.showConfirmDialog(null, "Error de conexión con el servidor", "Problema de conexión", JOptionPane.DEFAULT_OPTION, JOptionPane.WARNING_MESSAGE);
            }
   
        } else {
            JOptionPane.showConfirmDialog(null, "Es necesario llenar todos los campos", "Llenar Campos", JOptionPane.DEFAULT_OPTION, JOptionPane.INFORMATION_MESSAGE);
        }

        }
    }//GEN-LAST:event_btnLevantarDictamenActionPerformed

    private void txtLatitudActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtLatitudActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtLatitudActionPerformed

    private void txtLongitudActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtLongitudActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtLongitudActionPerformed

    private void btnLevantarDictamenKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_btnLevantarDictamenKeyPressed
          if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
              btnLevantarDictamenActionPerformed(null);
          }
    }//GEN-LAST:event_btnLevantarDictamenKeyPressed

    private void txtEstatusDictamenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtEstatusDictamenActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtEstatusDictamenActionPerformed

    private void txtOtroConductorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtOtroConductorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtOtroConductorActionPerformed

    private void txtDictamenKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtDictamenKeyTyped
        int limite = 254;
        if (txtDictamen.getText().length()== limite)
        evt.consume();
    }//GEN-LAST:event_txtDictamenKeyTyped

    private void btnSigImagenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSigImagenActionPerformed
        if (posicion == 0) {
            if (listaImagenes.size() > 0) {
                btnAntImagen.setEnabled(true);
                Icon icono = new ImageIcon(listaImagenes.get(1).getImage().getScaledInstance(lblImagen.getWidth(), lblImagen.getHeight(), Image.SCALE_DEFAULT));
                lblImagen.setIcon(icono);
                posicion++;
                if (listaImagenes.size() > posicion) {
                    btnSigImagen.setEnabled(false);
                }
            }
        } else if (listaImagenes.size() > posicion) {
            btnSigImagen.setEnabled(true);
            Icon icono = new ImageIcon(listaImagenes.get(posicion).getImage().getScaledInstance(lblImagen.getWidth(), lblImagen.getHeight(), Image.SCALE_DEFAULT));
            lblImagen.setIcon(icono);
            posicion++;
            if (listaImagenes.size() > posicion) {
                btnSigImagen.setEnabled(false);
            }
        }
    }//GEN-LAST:event_btnSigImagenActionPerformed

    private void btnAtrasKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_btnAtrasKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            btnAtrasActionPerformed(null);
        }
    }//GEN-LAST:event_btnAtrasKeyPressed

    private void btnAtrasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAtrasActionPerformed
         ConsultarReportesAsignados reportesAsignados = new ConsultarReportesAsignados(nombre, usuario, contrasena);
        reportesAsignados.setVisible(true);
        conexiones.cerrarConexion();
        this.dispose();
    }//GEN-LAST:event_btnAtrasActionPerformed

    private void btnAntImagenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAntImagenActionPerformed
       if (posicion == 0) {
           btnAntImagen.setEnabled(false);
           btnSigImagen.setEnabled(true);
        } else if (listaImagenes.size() > 0) {
            btnAntImagen.setEnabled(true);
            posicion--;
            Icon icono = new ImageIcon(listaImagenes.get(posicion).getImage().getScaledInstance(lblImagen.getWidth(), lblImagen.getHeight(), Image.SCALE_DEFAULT));
            lblImagen.setIcon(icono);
            if (posicion == 0) {
                btnAntImagen.setEnabled(false);
                btnSigImagen.setEnabled(true);
            }
        }
    }//GEN-LAST:event_btnAntImagenActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ConsultarReporte.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ConsultarReporte.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ConsultarReporte.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ConsultarReporte.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAntImagen;
    private javax.swing.JButton btnAtras;
    private javax.swing.JButton btnLevantarDictamen;
    private javax.swing.JButton btnSigImagen;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblConductor;
    private javax.swing.JLabel lblDeFecha;
    private javax.swing.JLabel lblDictamen;
    private javax.swing.JLabel lblEstatusDictamen1;
    private javax.swing.JLabel lblFechaDictamen;
    private javax.swing.JLabel lblImagen;
    private javax.swing.JLabel lblLatitud;
    private javax.swing.JLabel lblLongitud;
    private javax.swing.JLabel lblOtroConductor;
    private javax.swing.JLabel lblTitulo;
    private javax.swing.JMenu menuBienvenido;
    private javax.swing.JMenuItem menuCerrarSesion;
    private javax.swing.JTextArea txtDictamen;
    private javax.swing.JTextField txtEstatusDictamen;
    private javax.swing.JTextField txtLatitud;
    private javax.swing.JTextField txtLongitud;
    private javax.swing.JTextField txtOtroConductor;
    // End of variables declaration//GEN-END:variables
}
