/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vistas.Administrador;


import Thrift.Conexiones;
import Thrift.ErrorBD;
import Thrift.Funcionario;
import Vistas.Todos.IniciarSesion;
import java.awt.Image;
import java.awt.event.KeyEvent;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import org.apache.thrift.TException;


/**
 *
 * @author cris_
 */
public class CambiarContrasenaPerito extends javax.swing.JFrame {

    /**
     * Creates new form InicioPerito
     */
    Conexiones conexiones;
    String nombre, usuario, contrasena = null;
    /*Datos del funcionario que se modifica*/
    String usuarioPerito, nombrePerito;

    private void actualizarMenu() {
        String primerNombre = this.nombre.split(" ")[0].trim();
        menuBienvenido.setText("BIENVENIDO: " + primerNombre);
        conexiones = new Conexiones();
    }

    private void cerrarSesion() {
        IniciarSesion inicio = new IniciarSesion();
        inicio.setVisible(true);
        this.dispose();

    }

    public CambiarContrasenaPerito(String nombre, String usuario, String contrasena, String usuarioPerito, String nombrePerito) {
        initComponents();

        this.nombre = nombre;
        this.usuario = usuario;
        this.contrasena = contrasena;
        this.nombrePerito = nombrePerito;
        this.usuarioPerito = usuarioPerito;
        actualizarMenu();
        llenarCampos();

    }
    
    
    private void llenarCampos(){
        lblUsuario.setText("PERITO: " + nombrePerito);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        btnGuardarCambios = new javax.swing.JButton();
        lblUsuario = new javax.swing.JLabel();
        lblContrasena2 = new javax.swing.JLabel();
        lblContrasena3 = new javax.swing.JLabel();
        txtContrasena1 = new javax.swing.JPasswordField();
        txtContrasena2 = new javax.swing.JPasswordField();
        btnAtras = new javax.swing.JButton();
        lblTitulo = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        menuBienvenido = new javax.swing.JMenu();
        menuCerrarSesion = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Cambiar Contraseña");
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setLayout(null);

        btnGuardarCambios.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnGuardarCambios.setText("GUARDAR CAMBIOS");
        btnGuardarCambios.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btnGuardarCambios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarCambiosActionPerformed(evt);
            }
        });
        btnGuardarCambios.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                btnGuardarCambiosKeyPressed(evt);
            }
        });
        jPanel2.add(btnGuardarCambios);
        btnGuardarCambios.setBounds(360, 240, 180, 40);

        lblUsuario.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblUsuario.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblUsuario.setText("PERITO: NOMBRE COMPLETO");
        jPanel2.add(lblUsuario);
        lblUsuario.setBounds(20, 0, 530, 40);

        lblContrasena2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblContrasena2.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblContrasena2.setText("Confirmar Contraseña:");
        jPanel2.add(lblContrasena2);
        lblContrasena2.setBounds(0, 160, 150, 40);

        lblContrasena3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblContrasena3.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblContrasena3.setText("Contraseña:");
        jPanel2.add(lblContrasena3);
        lblContrasena3.setBounds(0, 80, 150, 40);

        txtContrasena1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jPanel2.add(txtContrasena1);
        txtContrasena1.setBounds(160, 80, 380, 40);

        txtContrasena2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jPanel2.add(txtContrasena2);
        txtContrasena2.setBounds(160, 160, 380, 40);

        btnAtras.setBackground(new java.awt.Color(255, 255, 255));
        btnAtras.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/back-arrow 24.png"))); // NOI18N
        btnAtras.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAtrasActionPerformed(evt);
            }
        });
        btnAtras.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                btnAtrasKeyPressed(evt);
            }
        });

        lblTitulo.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        lblTitulo.setText("CAMBIAR CONTRASEÑA");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addComponent(btnAtras)
                .addGap(217, 217, 217)
                .addComponent(lblTitulo)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(132, Short.MAX_VALUE)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 648, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(90, 90, 90))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnAtras, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblTitulo))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 38, Short.MAX_VALUE)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 342, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(33, 33, 33))
        );

        menuBienvenido.setText("BIENVENIDO JUAN");
        menuBienvenido.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N

        menuCerrarSesion.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/exit.png"))); // NOI18N
        menuCerrarSesion.setText("CERRAR SESIÓN");
        menuCerrarSesion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuCerrarSesionActionPerformed(evt);
            }
        });
        menuBienvenido.add(menuCerrarSesion);

        jMenuBar1.add(menuBienvenido);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void menuCerrarSesionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuCerrarSesionActionPerformed
         int confirmacion = JOptionPane.showConfirmDialog(null, "¿Desea cerrar la sesión actual?", "Cerrar Sesión",
                JOptionPane.YES_NO_OPTION, JOptionPane.INFORMATION_MESSAGE);
        if (confirmacion == 0) {
            cerrarSesion();
        }
    }//GEN-LAST:event_menuCerrarSesionActionPerformed

    private void btnGuardarCambiosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarCambiosActionPerformed
        String contrasena1, contrasena2;

        contrasena1 = new String(txtContrasena1.getPassword()).trim();
        contrasena2 = new String(txtContrasena2.getPassword()).trim();

        if ("".equals(contrasena1) || "".equals(contrasena2)) {
            JOptionPane.showConfirmDialog(null, "Es necesario llenar todos los campos", "Llenar Campos", JOptionPane.DEFAULT_OPTION, JOptionPane.INFORMATION_MESSAGE);
        } else {
            if (contrasena1.equals(contrasena2)) {
                if (contrasena1.length() > 7) {
                    try {
                        if (conexiones.cambiarContrasenaFuncionario(usuarioPerito, conexiones.getSHA256(contrasena1))) {
                            JOptionPane.showConfirmDialog(null, "Se han guardado los cambios exitosamente!!", "Modificación exitosa", JOptionPane.DEFAULT_OPTION, JOptionPane.INFORMATION_MESSAGE);
                            ConsultarPeritos consultarPeritos = new ConsultarPeritos(nombre, usuario, contrasena);
                            consultarPeritos.setVisible(true);
                            this.dispose();
                        } else {
                            JOptionPane.showConfirmDialog(null, "Ya existe un perito con ese nombre de usuario o hay un problema con la base de datos", "Error al guardar", JOptionPane.DEFAULT_OPTION, JOptionPane.INFORMATION_MESSAGE);
                        }
                    } catch (ErrorBD error) {
                        System.out.println("ERROR: " + error.codigoError + " " + error.problema);
                        JOptionPane.showConfirmDialog(null, "Sistema no diponible, intente más tarde", "Problema de conexión", JOptionPane.DEFAULT_OPTION, JOptionPane.WARNING_MESSAGE);
                    } catch (TException ex) {
                        conexiones.abrirConexion();
                        conexiones.cerrarConexion();
                        JOptionPane.showConfirmDialog(null, "Error al intentar modificar datos, intente de nuevo", "Error al guardar", JOptionPane.DEFAULT_OPTION, JOptionPane.INFORMATION_MESSAGE);
                    }
                } else {
                    JOptionPane.showConfirmDialog(null, "Las contraseñas deben ser de mínimo 8 caracteres", "Contraseña Inválida", JOptionPane.DEFAULT_OPTION, JOptionPane.INFORMATION_MESSAGE);
                }

            } else {
                JOptionPane.showConfirmDialog(null, "Las contraseñas no coinciden", "Contraseñas diferentes", JOptionPane.DEFAULT_OPTION, JOptionPane.INFORMATION_MESSAGE);
            }

        }


    }//GEN-LAST:event_btnGuardarCambiosActionPerformed

    private void btnAtrasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAtrasActionPerformed
        ConsultarPeritos consultarPeritos = new ConsultarPeritos(nombre, usuario, contrasena);
        consultarPeritos.setVisible(true);
        conexiones.cerrarConexion();
        this.dispose();
    }//GEN-LAST:event_btnAtrasActionPerformed

    private void btnGuardarCambiosKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_btnGuardarCambiosKeyPressed
          if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
              btnGuardarCambiosActionPerformed(null);
          }
    }//GEN-LAST:event_btnGuardarCambiosKeyPressed

    private void btnAtrasKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_btnAtrasKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
              btnAtrasActionPerformed(null);
          }
    }//GEN-LAST:event_btnAtrasKeyPressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CambiarContrasenaPerito.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CambiarContrasenaPerito.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CambiarContrasenaPerito.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CambiarContrasenaPerito.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAtras;
    private javax.swing.JButton btnGuardarCambios;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel lblContrasena2;
    private javax.swing.JLabel lblContrasena3;
    private javax.swing.JLabel lblTitulo;
    private javax.swing.JLabel lblUsuario;
    private javax.swing.JMenu menuBienvenido;
    private javax.swing.JMenuItem menuCerrarSesion;
    private javax.swing.JPasswordField txtContrasena1;
    private javax.swing.JPasswordField txtContrasena2;
    // End of variables declaration//GEN-END:variables
}
