/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vistas.Administrador;


import Thrift.Conexiones;
import Vistas.Todos.IniciarSesion;
import java.awt.Image;
import java.awt.event.KeyEvent;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;


/**
 *
 * @author cris_
 */
public class InicioAdministrador extends javax.swing.JFrame {

    /**
     * Creates new form InicioPerito
     */
    String nombre, usuario, contrasena = null;
    Conexiones conexiones;
    
    
    private void cargarIconos(){
        
        //Add Perito
        ImageIcon fot = new ImageIcon(this.getClass().getResource("/Imagenes/addPerito.png"));
        Icon icono = new ImageIcon(fot.getImage().getScaledInstance(lblAddPerito.getWidth(), lblAddPerito.getHeight(), Image.SCALE_DEFAULT));
        lblAddPerito.setIcon(icono);
        
        //Consultar Peritos
        fot = new ImageIcon(this.getClass().getResource("/Imagenes/consultarPeritos.png"));
        icono = new ImageIcon(fot.getImage().getScaledInstance(lblConsultarPeritos.getWidth(), lblConsultarPeritos.getHeight(), Image.SCALE_DEFAULT));
        lblConsultarPeritos.setIcon(icono);
        this.repaint();
        
        conexiones = new Conexiones();
    }
    
    private void actualizarMenu(){      
        String primerNombre = this.nombre.split(" ")[0].trim();
        menuBienvenido.setText("BIENVENIDO: " + primerNombre);
    }
    
    private void cerrarSesion(){
        IniciarSesion inicio = new IniciarSesion();
        inicio.setVisible(true);
        this.dispose();
        
    }
    
    
    public InicioAdministrador(String nombre, String usuario, String contrasena) {
        initComponents();
        cargarIconos();
        this.nombre = nombre;
        this.usuario = usuario;
        this.contrasena = contrasena;
        actualizarMenu();
        

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        lblAddPerito = new javax.swing.JLabel();
        lblConsultarPeritos = new javax.swing.JLabel();
        btnRegistrarPerito = new javax.swing.JButton();
        btnConsultarPeritos = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        menuBienvenido = new javax.swing.JMenu();
        menuCerrarSesion = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Inicio Administrador");
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/GOBMX.png"))); // NOI18N

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setLayout(null);

        lblAddPerito.setLabelFor(btnRegistrarPerito);
        jPanel2.add(lblAddPerito);
        lblAddPerito.setBounds(240, 30, 150, 118);

        lblConsultarPeritos.setLabelFor(btnConsultarPeritos);
        jPanel2.add(lblConsultarPeritos);
        lblConsultarPeritos.setBounds(450, 30, 160, 130);

        btnRegistrarPerito.setText("REGISTRAR PERITO");
        btnRegistrarPerito.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btnRegistrarPerito.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegistrarPeritoActionPerformed(evt);
            }
        });
        btnRegistrarPerito.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                btnRegistrarPeritoKeyPressed(evt);
            }
        });
        jPanel2.add(btnRegistrarPerito);
        btnRegistrarPerito.setBounds(240, 180, 150, 40);

        btnConsultarPeritos.setText("CONSULTAR PERITOS");
        btnConsultarPeritos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConsultarPeritosActionPerformed(evt);
            }
        });
        btnConsultarPeritos.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                btnConsultarPeritosKeyPressed(evt);
            }
        });
        jPanel2.add(btnConsultarPeritos);
        btnConsultarPeritos.setBounds(450, 180, 160, 40);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 870, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 236, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(73, Short.MAX_VALUE))
        );

        menuBienvenido.setText("BIENVENIDO JUAN");
        menuBienvenido.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N

        menuCerrarSesion.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/exit.png"))); // NOI18N
        menuCerrarSesion.setText("CERRAR SESIÓN");
        menuCerrarSesion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuCerrarSesionActionPerformed(evt);
            }
        });
        menuBienvenido.add(menuCerrarSesion);

        jMenuBar1.add(menuBienvenido);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void menuCerrarSesionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuCerrarSesionActionPerformed
        int confirmacion = JOptionPane.showConfirmDialog(null, "¿Desea cerrar la sesión actual?", "Cerrar Sesión",
                JOptionPane.YES_NO_OPTION, JOptionPane.INFORMATION_MESSAGE);
        if (confirmacion == 0) {
            cerrarSesion();
        }
    }//GEN-LAST:event_menuCerrarSesionActionPerformed

    private void btnRegistrarPeritoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegistrarPeritoActionPerformed
        RegistrarPerito registrarPerito = new RegistrarPerito(this.nombre, this.usuario, this.contrasena);
        registrarPerito.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnRegistrarPeritoActionPerformed

    private void btnConsultarPeritosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConsultarPeritosActionPerformed
        ConsultarPeritos consultarPeritos = new ConsultarPeritos(nombre, usuario, contrasena);
        consultarPeritos.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnConsultarPeritosActionPerformed

    private void btnRegistrarPeritoKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_btnRegistrarPeritoKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
              btnRegistrarPeritoActionPerformed(null);
          }
    }//GEN-LAST:event_btnRegistrarPeritoKeyPressed

    private void btnConsultarPeritosKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_btnConsultarPeritosKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
              btnConsultarPeritosActionPerformed(null);
          }
    }//GEN-LAST:event_btnConsultarPeritosKeyPressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(InicioAdministrador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(InicioAdministrador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(InicioAdministrador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(InicioAdministrador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnConsultarPeritos;
    private javax.swing.JButton btnRegistrarPerito;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel lblAddPerito;
    private javax.swing.JLabel lblConsultarPeritos;
    private javax.swing.JMenu menuBienvenido;
    private javax.swing.JMenuItem menuCerrarSesion;
    // End of variables declaration//GEN-END:variables
}
