/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vistas.Todos;

import Thrift.Conexiones;
import Thrift.ErrorBD;
import Thrift.Funcionario;
import Vistas.Administrador.InicioAdministrador;
import Vistas.Perito.InicioPerito;
import java.awt.event.KeyEvent;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import org.apache.thrift.TException;

/**
 *
 * @author cris_
 */
public class IniciarSesion extends javax.swing.JFrame {

    Conexiones conexiones;

    /**
     * Creates new form IniciarSesion
     */
    public IniciarSesion() {
        initComponents();
        conexiones = new Conexiones();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        txtUsuario = new javax.swing.JTextField();
        lblUsuario = new javax.swing.JLabel();
        lblContrasena = new javax.swing.JLabel();
        btnIngresar = new javax.swing.JButton();
        lblLogo = new javax.swing.JLabel();
        txtContrasena = new javax.swing.JPasswordField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Inicio de Sesion");
        setPreferredSize(new java.awt.Dimension(870, 500));
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(null);

        txtUsuario.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtUsuario.setToolTipText("");
        txtUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtUsuarioActionPerformed(evt);
            }
        });
        txtUsuario.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtUsuarioKeyTyped(evt);
            }
        });
        jPanel1.add(txtUsuario);
        txtUsuario.setBounds(240, 210, 377, 38);

        lblUsuario.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lblUsuario.setText("Usuario");
        jPanel1.add(lblUsuario);
        lblUsuario.setBounds(240, 170, 110, 30);

        lblContrasena.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lblContrasena.setText("Contraseña");
        jPanel1.add(lblContrasena);
        lblContrasena.setBounds(240, 270, 110, 30);

        btnIngresar.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnIngresar.setText("INGRESAR");
        btnIngresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIngresarActionPerformed(evt);
            }
        });
        btnIngresar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                btnIngresarKeyPressed(evt);
            }
        });
        jPanel1.add(btnIngresar);
        btnIngresar.setBounds(493, 370, 120, 30);

        lblLogo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/GOBMX.png"))); // NOI18N
        lblLogo.setToolTipText("");
        jPanel1.add(lblLogo);
        lblLogo.setBounds(320, 30, 210, 120);

        txtContrasena.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtContrasenaKeyPressed(evt);
            }
        });
        jPanel1.add(txtContrasena);
        txtContrasena.setBounds(240, 310, 377, 38);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 870, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 470, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void txtUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtUsuarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtUsuarioActionPerformed

    private void btnIngresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIngresarActionPerformed
        String usuario = txtUsuario.getText().toUpperCase();
        String contrasena = new String(txtContrasena.getPassword());
        String cargo;
        String nombre;
        int estatus;
        contrasena = conexiones.getSHA256(contrasena);
        Funcionario funcionario;

        if ("".equals(usuario) || "".equals(contrasena)) {
            JOptionPane.showConfirmDialog(null, "Es necesario llenar todos los campos", "Llenar Campos", JOptionPane.DEFAULT_OPTION, JOptionPane.INFORMATION_MESSAGE);
        } else {

            try {
                
                /*Verifica el usuario y contraseña del funcionario*/    
                if (conexiones.verificarFuncionario(usuario, contrasena)) {
                    funcionario = conexiones.getFuncionario(usuario);
                    cargo = funcionario.getCargo();
                    nombre = funcionario.getNombre();
                    estatus = funcionario.getEstatus();
                    
                    if(estatus == 1){
                        switch (cargo) {
                        case "ADMINISTRADOR":
                            //Se pasa el usuario, contraseña y nombre
                            InicioAdministrador inicioAdministrador = new InicioAdministrador(nombre, usuario, contrasena);
                            inicioAdministrador.setVisible(true);
                            conexiones.cerrarConexion();
                            this.dispose();
                            break;
                        case "PERITO":
                            //Si no es administrador es un perito
                            InicioPerito inicioPerito = new InicioPerito(nombre, usuario, contrasena);
                            inicioPerito.setVisible(true);
                            conexiones.cerrarConexion();
                            this.dispose();
                            break;
                        default:
                            JOptionPane.showConfirmDialog(null, "Usuario Inválido", "Usuario sin permisos", JOptionPane.DEFAULT_OPTION, JOptionPane.ERROR_MESSAGE);
                            break;
                    }
                    }else{
                        JOptionPane.showConfirmDialog(null, "Su cuenta ha sido suspendida, contactar con el administrador", "Cuenta Suspendida", JOptionPane.DEFAULT_OPTION, JOptionPane.INFORMATION_MESSAGE);
                    }
                } else {
                    JOptionPane.showConfirmDialog(null, "Nombre de usuario y/o contraseña incorrectos", "Datos inválidos", JOptionPane.DEFAULT_OPTION, JOptionPane.INFORMATION_MESSAGE);
                }
            } catch (ErrorBD error){
                System.out.println("ERROR: " + error.codigoError + " " + error.problema);
               JOptionPane.showConfirmDialog(null, "Error de conexión con con la base de datos", "Problema de conexión", JOptionPane.DEFAULT_OPTION, JOptionPane.WARNING_MESSAGE);
            } catch (TException ex) {
                conexiones.abrirConexion();
                conexiones.cerrarConexion();
                JOptionPane.showConfirmDialog(null, "Error de conexión con el servidor", "Problema de conexión", JOptionPane.DEFAULT_OPTION, JOptionPane.WARNING_MESSAGE);
            } 

        }



    }//GEN-LAST:event_btnIngresarActionPerformed

    private void btnIngresarKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_btnIngresarKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
              btnIngresarActionPerformed(null);
        }
    }//GEN-LAST:event_btnIngresarKeyPressed

    private void txtContrasenaKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtContrasenaKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
              btnIngresarActionPerformed(null);
        }
    }//GEN-LAST:event_txtContrasenaKeyPressed

    private void txtUsuarioKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtUsuarioKeyTyped
        int limite = 40;
        if (txtUsuario.getText().length() == limite) {
            evt.consume();
        }
           
    }//GEN-LAST:event_txtUsuarioKeyTyped

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(IniciarSesion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(IniciarSesion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(IniciarSesion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(IniciarSesion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new IniciarSesion().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnIngresar;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblContrasena;
    private javax.swing.JLabel lblLogo;
    private javax.swing.JLabel lblUsuario;
    private javax.swing.JPasswordField txtContrasena;
    private javax.swing.JTextField txtUsuario;
    // End of variables declaration//GEN-END:variables
}
