/**
 * Autogenerated by Thrift Compiler (0.12.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
package Thrift;

@SuppressWarnings({"cast", "rawtypes", "serial", "unchecked", "unused"})
//@javax.annotation.Generated(value = "Autogenerated by Thrift Compiler (0.12.0)", date = "2019-06-27")
public class Reporte implements org.apache.thrift.TBase<Reporte, Reporte._Fields>, java.io.Serializable, Cloneable, Comparable<Reporte> {
  private static final org.apache.thrift.protocol.TStruct STRUCT_DESC = new org.apache.thrift.protocol.TStruct("Reporte");

  private static final org.apache.thrift.protocol.TField LATITUD_FIELD_DESC = new org.apache.thrift.protocol.TField("latitud", org.apache.thrift.protocol.TType.STRING, (short)1);
  private static final org.apache.thrift.protocol.TField LONGITUD_FIELD_DESC = new org.apache.thrift.protocol.TField("longitud", org.apache.thrift.protocol.TType.STRING, (short)2);
  private static final org.apache.thrift.protocol.TField NOMBRE_OTRO_CONDUC_FIELD_DESC = new org.apache.thrift.protocol.TField("nombreOtroConduc", org.apache.thrift.protocol.TType.STRING, (short)3);
  private static final org.apache.thrift.protocol.TField IDCONDUCTOR1_FIELD_DESC = new org.apache.thrift.protocol.TField("idconductor1", org.apache.thrift.protocol.TType.I32, (short)4);
  private static final org.apache.thrift.protocol.TField FOLIO_UNICO_DICTAMEN_FIELD_DESC = new org.apache.thrift.protocol.TField("folioUnico_dictamen", org.apache.thrift.protocol.TType.I32, (short)5);
  private static final org.apache.thrift.protocol.TField ID_FUNCIONARIO_FIELD_DESC = new org.apache.thrift.protocol.TField("idFuncionario", org.apache.thrift.protocol.TType.I32, (short)6);

  private static final org.apache.thrift.scheme.SchemeFactory STANDARD_SCHEME_FACTORY = new ReporteStandardSchemeFactory();
  private static final org.apache.thrift.scheme.SchemeFactory TUPLE_SCHEME_FACTORY = new ReporteTupleSchemeFactory();

  public @org.apache.thrift.annotation.Nullable java.lang.String latitud; // required
  public @org.apache.thrift.annotation.Nullable java.lang.String longitud; // required
  public @org.apache.thrift.annotation.Nullable java.lang.String nombreOtroConduc; // required
  public int idconductor1; // required
  public int folioUnico_dictamen; // required
  public int idFuncionario; // required

  /** The set of fields this struct contains, along with convenience methods for finding and manipulating them. */
  public enum _Fields implements org.apache.thrift.TFieldIdEnum {
    LATITUD((short)1, "latitud"),
    LONGITUD((short)2, "longitud"),
    NOMBRE_OTRO_CONDUC((short)3, "nombreOtroConduc"),
    IDCONDUCTOR1((short)4, "idconductor1"),
    FOLIO_UNICO_DICTAMEN((short)5, "folioUnico_dictamen"),
    ID_FUNCIONARIO((short)6, "idFuncionario");

    private static final java.util.Map<java.lang.String, _Fields> byName = new java.util.HashMap<java.lang.String, _Fields>();

    static {
      for (_Fields field : java.util.EnumSet.allOf(_Fields.class)) {
        byName.put(field.getFieldName(), field);
      }
    }

    /**
     * Find the _Fields constant that matches fieldId, or null if its not found.
     */
    @org.apache.thrift.annotation.Nullable
    public static _Fields findByThriftId(int fieldId) {
      switch(fieldId) {
        case 1: // LATITUD
          return LATITUD;
        case 2: // LONGITUD
          return LONGITUD;
        case 3: // NOMBRE_OTRO_CONDUC
          return NOMBRE_OTRO_CONDUC;
        case 4: // IDCONDUCTOR1
          return IDCONDUCTOR1;
        case 5: // FOLIO_UNICO_DICTAMEN
          return FOLIO_UNICO_DICTAMEN;
        case 6: // ID_FUNCIONARIO
          return ID_FUNCIONARIO;
        default:
          return null;
      }
    }

    /**
     * Find the _Fields constant that matches fieldId, throwing an exception
     * if it is not found.
     */
    public static _Fields findByThriftIdOrThrow(int fieldId) {
      _Fields fields = findByThriftId(fieldId);
      if (fields == null) throw new java.lang.IllegalArgumentException("Field " + fieldId + " doesn't exist!");
      return fields;
    }

    /**
     * Find the _Fields constant that matches name, or null if its not found.
     */
    @org.apache.thrift.annotation.Nullable
    public static _Fields findByName(java.lang.String name) {
      return byName.get(name);
    }

    private final short _thriftId;
    private final java.lang.String _fieldName;

    _Fields(short thriftId, java.lang.String fieldName) {
      _thriftId = thriftId;
      _fieldName = fieldName;
    }

    public short getThriftFieldId() {
      return _thriftId;
    }

    public java.lang.String getFieldName() {
      return _fieldName;
    }
  }

  // isset id assignments
  private static final int __IDCONDUCTOR1_ISSET_ID = 0;
  private static final int __FOLIOUNICO_DICTAMEN_ISSET_ID = 1;
  private static final int __IDFUNCIONARIO_ISSET_ID = 2;
  private byte __isset_bitfield = 0;
  public static final java.util.Map<_Fields, org.apache.thrift.meta_data.FieldMetaData> metaDataMap;
  static {
    java.util.Map<_Fields, org.apache.thrift.meta_data.FieldMetaData> tmpMap = new java.util.EnumMap<_Fields, org.apache.thrift.meta_data.FieldMetaData>(_Fields.class);
    tmpMap.put(_Fields.LATITUD, new org.apache.thrift.meta_data.FieldMetaData("latitud", org.apache.thrift.TFieldRequirementType.DEFAULT, 
        new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.STRING)));
    tmpMap.put(_Fields.LONGITUD, new org.apache.thrift.meta_data.FieldMetaData("longitud", org.apache.thrift.TFieldRequirementType.DEFAULT, 
        new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.STRING)));
    tmpMap.put(_Fields.NOMBRE_OTRO_CONDUC, new org.apache.thrift.meta_data.FieldMetaData("nombreOtroConduc", org.apache.thrift.TFieldRequirementType.DEFAULT, 
        new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.STRING)));
    tmpMap.put(_Fields.IDCONDUCTOR1, new org.apache.thrift.meta_data.FieldMetaData("idconductor1", org.apache.thrift.TFieldRequirementType.DEFAULT, 
        new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.I32)));
    tmpMap.put(_Fields.FOLIO_UNICO_DICTAMEN, new org.apache.thrift.meta_data.FieldMetaData("folioUnico_dictamen", org.apache.thrift.TFieldRequirementType.DEFAULT, 
        new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.I32)));
    tmpMap.put(_Fields.ID_FUNCIONARIO, new org.apache.thrift.meta_data.FieldMetaData("idFuncionario", org.apache.thrift.TFieldRequirementType.DEFAULT, 
        new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.I32)));
    metaDataMap = java.util.Collections.unmodifiableMap(tmpMap);
    org.apache.thrift.meta_data.FieldMetaData.addStructMetaDataMap(Reporte.class, metaDataMap);
  }

  public Reporte() {
  }

  public Reporte(
    java.lang.String latitud,
    java.lang.String longitud,
    java.lang.String nombreOtroConduc,
    int idconductor1,
    int folioUnico_dictamen,
    int idFuncionario)
  {
    this();
    this.latitud = latitud;
    this.longitud = longitud;
    this.nombreOtroConduc = nombreOtroConduc;
    this.idconductor1 = idconductor1;
    setIdconductor1IsSet(true);
    this.folioUnico_dictamen = folioUnico_dictamen;
    setFolioUnico_dictamenIsSet(true);
    this.idFuncionario = idFuncionario;
    setIdFuncionarioIsSet(true);
  }

  /**
   * Performs a deep copy on <i>other</i>.
   */
  public Reporte(Reporte other) {
    __isset_bitfield = other.__isset_bitfield;
    if (other.isSetLatitud()) {
      this.latitud = other.latitud;
    }
    if (other.isSetLongitud()) {
      this.longitud = other.longitud;
    }
    if (other.isSetNombreOtroConduc()) {
      this.nombreOtroConduc = other.nombreOtroConduc;
    }
    this.idconductor1 = other.idconductor1;
    this.folioUnico_dictamen = other.folioUnico_dictamen;
    this.idFuncionario = other.idFuncionario;
  }

  public Reporte deepCopy() {
    return new Reporte(this);
  }

  @Override
  public void clear() {
    this.latitud = null;
    this.longitud = null;
    this.nombreOtroConduc = null;
    setIdconductor1IsSet(false);
    this.idconductor1 = 0;
    setFolioUnico_dictamenIsSet(false);
    this.folioUnico_dictamen = 0;
    setIdFuncionarioIsSet(false);
    this.idFuncionario = 0;
  }

  @org.apache.thrift.annotation.Nullable
  public java.lang.String getLatitud() {
    return this.latitud;
  }

  public Reporte setLatitud(@org.apache.thrift.annotation.Nullable java.lang.String latitud) {
    this.latitud = latitud;
    return this;
  }

  public void unsetLatitud() {
    this.latitud = null;
  }

  /** Returns true if field latitud is set (has been assigned a value) and false otherwise */
  public boolean isSetLatitud() {
    return this.latitud != null;
  }

  public void setLatitudIsSet(boolean value) {
    if (!value) {
      this.latitud = null;
    }
  }

  @org.apache.thrift.annotation.Nullable
  public java.lang.String getLongitud() {
    return this.longitud;
  }

  public Reporte setLongitud(@org.apache.thrift.annotation.Nullable java.lang.String longitud) {
    this.longitud = longitud;
    return this;
  }

  public void unsetLongitud() {
    this.longitud = null;
  }

  /** Returns true if field longitud is set (has been assigned a value) and false otherwise */
  public boolean isSetLongitud() {
    return this.longitud != null;
  }

  public void setLongitudIsSet(boolean value) {
    if (!value) {
      this.longitud = null;
    }
  }

  @org.apache.thrift.annotation.Nullable
  public java.lang.String getNombreOtroConduc() {
    return this.nombreOtroConduc;
  }

  public Reporte setNombreOtroConduc(@org.apache.thrift.annotation.Nullable java.lang.String nombreOtroConduc) {
    this.nombreOtroConduc = nombreOtroConduc;
    return this;
  }

  public void unsetNombreOtroConduc() {
    this.nombreOtroConduc = null;
  }

  /** Returns true if field nombreOtroConduc is set (has been assigned a value) and false otherwise */
  public boolean isSetNombreOtroConduc() {
    return this.nombreOtroConduc != null;
  }

  public void setNombreOtroConducIsSet(boolean value) {
    if (!value) {
      this.nombreOtroConduc = null;
    }
  }

  public int getIdconductor1() {
    return this.idconductor1;
  }

  public Reporte setIdconductor1(int idconductor1) {
    this.idconductor1 = idconductor1;
    setIdconductor1IsSet(true);
    return this;
  }

  public void unsetIdconductor1() {
    __isset_bitfield = org.apache.thrift.EncodingUtils.clearBit(__isset_bitfield, __IDCONDUCTOR1_ISSET_ID);
  }

  /** Returns true if field idconductor1 is set (has been assigned a value) and false otherwise */
  public boolean isSetIdconductor1() {
    return org.apache.thrift.EncodingUtils.testBit(__isset_bitfield, __IDCONDUCTOR1_ISSET_ID);
  }

  public void setIdconductor1IsSet(boolean value) {
    __isset_bitfield = org.apache.thrift.EncodingUtils.setBit(__isset_bitfield, __IDCONDUCTOR1_ISSET_ID, value);
  }

  public int getFolioUnico_dictamen() {
    return this.folioUnico_dictamen;
  }

  public Reporte setFolioUnico_dictamen(int folioUnico_dictamen) {
    this.folioUnico_dictamen = folioUnico_dictamen;
    setFolioUnico_dictamenIsSet(true);
    return this;
  }

  public void unsetFolioUnico_dictamen() {
    __isset_bitfield = org.apache.thrift.EncodingUtils.clearBit(__isset_bitfield, __FOLIOUNICO_DICTAMEN_ISSET_ID);
  }

  /** Returns true if field folioUnico_dictamen is set (has been assigned a value) and false otherwise */
  public boolean isSetFolioUnico_dictamen() {
    return org.apache.thrift.EncodingUtils.testBit(__isset_bitfield, __FOLIOUNICO_DICTAMEN_ISSET_ID);
  }

  public void setFolioUnico_dictamenIsSet(boolean value) {
    __isset_bitfield = org.apache.thrift.EncodingUtils.setBit(__isset_bitfield, __FOLIOUNICO_DICTAMEN_ISSET_ID, value);
  }

  public int getIdFuncionario() {
    return this.idFuncionario;
  }

  public Reporte setIdFuncionario(int idFuncionario) {
    this.idFuncionario = idFuncionario;
    setIdFuncionarioIsSet(true);
    return this;
  }

  public void unsetIdFuncionario() {
    __isset_bitfield = org.apache.thrift.EncodingUtils.clearBit(__isset_bitfield, __IDFUNCIONARIO_ISSET_ID);
  }

  /** Returns true if field idFuncionario is set (has been assigned a value) and false otherwise */
  public boolean isSetIdFuncionario() {
    return org.apache.thrift.EncodingUtils.testBit(__isset_bitfield, __IDFUNCIONARIO_ISSET_ID);
  }

  public void setIdFuncionarioIsSet(boolean value) {
    __isset_bitfield = org.apache.thrift.EncodingUtils.setBit(__isset_bitfield, __IDFUNCIONARIO_ISSET_ID, value);
  }

  public void setFieldValue(_Fields field, @org.apache.thrift.annotation.Nullable java.lang.Object value) {
    switch (field) {
    case LATITUD:
      if (value == null) {
        unsetLatitud();
      } else {
        setLatitud((java.lang.String)value);
      }
      break;

    case LONGITUD:
      if (value == null) {
        unsetLongitud();
      } else {
        setLongitud((java.lang.String)value);
      }
      break;

    case NOMBRE_OTRO_CONDUC:
      if (value == null) {
        unsetNombreOtroConduc();
      } else {
        setNombreOtroConduc((java.lang.String)value);
      }
      break;

    case IDCONDUCTOR1:
      if (value == null) {
        unsetIdconductor1();
      } else {
        setIdconductor1((java.lang.Integer)value);
      }
      break;

    case FOLIO_UNICO_DICTAMEN:
      if (value == null) {
        unsetFolioUnico_dictamen();
      } else {
        setFolioUnico_dictamen((java.lang.Integer)value);
      }
      break;

    case ID_FUNCIONARIO:
      if (value == null) {
        unsetIdFuncionario();
      } else {
        setIdFuncionario((java.lang.Integer)value);
      }
      break;

    }
  }

  @org.apache.thrift.annotation.Nullable
  public java.lang.Object getFieldValue(_Fields field) {
    switch (field) {
    case LATITUD:
      return getLatitud();

    case LONGITUD:
      return getLongitud();

    case NOMBRE_OTRO_CONDUC:
      return getNombreOtroConduc();

    case IDCONDUCTOR1:
      return getIdconductor1();

    case FOLIO_UNICO_DICTAMEN:
      return getFolioUnico_dictamen();

    case ID_FUNCIONARIO:
      return getIdFuncionario();

    }
    throw new java.lang.IllegalStateException();
  }

  /** Returns true if field corresponding to fieldID is set (has been assigned a value) and false otherwise */
  public boolean isSet(_Fields field) {
    if (field == null) {
      throw new java.lang.IllegalArgumentException();
    }

    switch (field) {
    case LATITUD:
      return isSetLatitud();
    case LONGITUD:
      return isSetLongitud();
    case NOMBRE_OTRO_CONDUC:
      return isSetNombreOtroConduc();
    case IDCONDUCTOR1:
      return isSetIdconductor1();
    case FOLIO_UNICO_DICTAMEN:
      return isSetFolioUnico_dictamen();
    case ID_FUNCIONARIO:
      return isSetIdFuncionario();
    }
    throw new java.lang.IllegalStateException();
  }

  @Override
  public boolean equals(java.lang.Object that) {
    if (that == null)
      return false;
    if (that instanceof Reporte)
      return this.equals((Reporte)that);
    return false;
  }

  public boolean equals(Reporte that) {
    if (that == null)
      return false;
    if (this == that)
      return true;

    boolean this_present_latitud = true && this.isSetLatitud();
    boolean that_present_latitud = true && that.isSetLatitud();
    if (this_present_latitud || that_present_latitud) {
      if (!(this_present_latitud && that_present_latitud))
        return false;
      if (!this.latitud.equals(that.latitud))
        return false;
    }

    boolean this_present_longitud = true && this.isSetLongitud();
    boolean that_present_longitud = true && that.isSetLongitud();
    if (this_present_longitud || that_present_longitud) {
      if (!(this_present_longitud && that_present_longitud))
        return false;
      if (!this.longitud.equals(that.longitud))
        return false;
    }

    boolean this_present_nombreOtroConduc = true && this.isSetNombreOtroConduc();
    boolean that_present_nombreOtroConduc = true && that.isSetNombreOtroConduc();
    if (this_present_nombreOtroConduc || that_present_nombreOtroConduc) {
      if (!(this_present_nombreOtroConduc && that_present_nombreOtroConduc))
        return false;
      if (!this.nombreOtroConduc.equals(that.nombreOtroConduc))
        return false;
    }

    boolean this_present_idconductor1 = true;
    boolean that_present_idconductor1 = true;
    if (this_present_idconductor1 || that_present_idconductor1) {
      if (!(this_present_idconductor1 && that_present_idconductor1))
        return false;
      if (this.idconductor1 != that.idconductor1)
        return false;
    }

    boolean this_present_folioUnico_dictamen = true;
    boolean that_present_folioUnico_dictamen = true;
    if (this_present_folioUnico_dictamen || that_present_folioUnico_dictamen) {
      if (!(this_present_folioUnico_dictamen && that_present_folioUnico_dictamen))
        return false;
      if (this.folioUnico_dictamen != that.folioUnico_dictamen)
        return false;
    }

    boolean this_present_idFuncionario = true;
    boolean that_present_idFuncionario = true;
    if (this_present_idFuncionario || that_present_idFuncionario) {
      if (!(this_present_idFuncionario && that_present_idFuncionario))
        return false;
      if (this.idFuncionario != that.idFuncionario)
        return false;
    }

    return true;
  }

  @Override
  public int hashCode() {
    int hashCode = 1;

    hashCode = hashCode * 8191 + ((isSetLatitud()) ? 131071 : 524287);
    if (isSetLatitud())
      hashCode = hashCode * 8191 + latitud.hashCode();

    hashCode = hashCode * 8191 + ((isSetLongitud()) ? 131071 : 524287);
    if (isSetLongitud())
      hashCode = hashCode * 8191 + longitud.hashCode();

    hashCode = hashCode * 8191 + ((isSetNombreOtroConduc()) ? 131071 : 524287);
    if (isSetNombreOtroConduc())
      hashCode = hashCode * 8191 + nombreOtroConduc.hashCode();

    hashCode = hashCode * 8191 + idconductor1;

    hashCode = hashCode * 8191 + folioUnico_dictamen;

    hashCode = hashCode * 8191 + idFuncionario;

    return hashCode;
  }

  @Override
  public int compareTo(Reporte other) {
    if (!getClass().equals(other.getClass())) {
      return getClass().getName().compareTo(other.getClass().getName());
    }

    int lastComparison = 0;

    lastComparison = java.lang.Boolean.valueOf(isSetLatitud()).compareTo(other.isSetLatitud());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetLatitud()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.latitud, other.latitud);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = java.lang.Boolean.valueOf(isSetLongitud()).compareTo(other.isSetLongitud());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetLongitud()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.longitud, other.longitud);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = java.lang.Boolean.valueOf(isSetNombreOtroConduc()).compareTo(other.isSetNombreOtroConduc());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetNombreOtroConduc()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.nombreOtroConduc, other.nombreOtroConduc);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = java.lang.Boolean.valueOf(isSetIdconductor1()).compareTo(other.isSetIdconductor1());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetIdconductor1()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.idconductor1, other.idconductor1);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = java.lang.Boolean.valueOf(isSetFolioUnico_dictamen()).compareTo(other.isSetFolioUnico_dictamen());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetFolioUnico_dictamen()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.folioUnico_dictamen, other.folioUnico_dictamen);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = java.lang.Boolean.valueOf(isSetIdFuncionario()).compareTo(other.isSetIdFuncionario());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetIdFuncionario()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.idFuncionario, other.idFuncionario);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    return 0;
  }

  @org.apache.thrift.annotation.Nullable
  public _Fields fieldForId(int fieldId) {
    return _Fields.findByThriftId(fieldId);
  }

  public void read(org.apache.thrift.protocol.TProtocol iprot) throws org.apache.thrift.TException {
    scheme(iprot).read(iprot, this);
  }

  public void write(org.apache.thrift.protocol.TProtocol oprot) throws org.apache.thrift.TException {
    scheme(oprot).write(oprot, this);
  }

  @Override
  public java.lang.String toString() {
    java.lang.StringBuilder sb = new java.lang.StringBuilder("Reporte(");
    boolean first = true;

    sb.append("latitud:");
    if (this.latitud == null) {
      sb.append("null");
    } else {
      sb.append(this.latitud);
    }
    first = false;
    if (!first) sb.append(", ");
    sb.append("longitud:");
    if (this.longitud == null) {
      sb.append("null");
    } else {
      sb.append(this.longitud);
    }
    first = false;
    if (!first) sb.append(", ");
    sb.append("nombreOtroConduc:");
    if (this.nombreOtroConduc == null) {
      sb.append("null");
    } else {
      sb.append(this.nombreOtroConduc);
    }
    first = false;
    if (!first) sb.append(", ");
    sb.append("idconductor1:");
    sb.append(this.idconductor1);
    first = false;
    if (!first) sb.append(", ");
    sb.append("folioUnico_dictamen:");
    sb.append(this.folioUnico_dictamen);
    first = false;
    if (!first) sb.append(", ");
    sb.append("idFuncionario:");
    sb.append(this.idFuncionario);
    first = false;
    sb.append(")");
    return sb.toString();
  }

  public void validate() throws org.apache.thrift.TException {
    // check for required fields
    // check for sub-struct validity
  }

  private void writeObject(java.io.ObjectOutputStream out) throws java.io.IOException {
    try {
      write(new org.apache.thrift.protocol.TCompactProtocol(new org.apache.thrift.transport.TIOStreamTransport(out)));
    } catch (org.apache.thrift.TException te) {
      throw new java.io.IOException(te);
    }
  }

  private void readObject(java.io.ObjectInputStream in) throws java.io.IOException, java.lang.ClassNotFoundException {
    try {
      // it doesn't seem like you should have to do this, but java serialization is wacky, and doesn't call the default constructor.
      __isset_bitfield = 0;
      read(new org.apache.thrift.protocol.TCompactProtocol(new org.apache.thrift.transport.TIOStreamTransport(in)));
    } catch (org.apache.thrift.TException te) {
      throw new java.io.IOException(te);
    }
  }

  private static class ReporteStandardSchemeFactory implements org.apache.thrift.scheme.SchemeFactory {
    public ReporteStandardScheme getScheme() {
      return new ReporteStandardScheme();
    }
  }

  private static class ReporteStandardScheme extends org.apache.thrift.scheme.StandardScheme<Reporte> {

    public void read(org.apache.thrift.protocol.TProtocol iprot, Reporte struct) throws org.apache.thrift.TException {
      org.apache.thrift.protocol.TField schemeField;
      iprot.readStructBegin();
      while (true)
      {
        schemeField = iprot.readFieldBegin();
        if (schemeField.type == org.apache.thrift.protocol.TType.STOP) { 
          break;
        }
        switch (schemeField.id) {
          case 1: // LATITUD
            if (schemeField.type == org.apache.thrift.protocol.TType.STRING) {
              struct.latitud = iprot.readString();
              struct.setLatitudIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          case 2: // LONGITUD
            if (schemeField.type == org.apache.thrift.protocol.TType.STRING) {
              struct.longitud = iprot.readString();
              struct.setLongitudIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          case 3: // NOMBRE_OTRO_CONDUC
            if (schemeField.type == org.apache.thrift.protocol.TType.STRING) {
              struct.nombreOtroConduc = iprot.readString();
              struct.setNombreOtroConducIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          case 4: // IDCONDUCTOR1
            if (schemeField.type == org.apache.thrift.protocol.TType.I32) {
              struct.idconductor1 = iprot.readI32();
              struct.setIdconductor1IsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          case 5: // FOLIO_UNICO_DICTAMEN
            if (schemeField.type == org.apache.thrift.protocol.TType.I32) {
              struct.folioUnico_dictamen = iprot.readI32();
              struct.setFolioUnico_dictamenIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          case 6: // ID_FUNCIONARIO
            if (schemeField.type == org.apache.thrift.protocol.TType.I32) {
              struct.idFuncionario = iprot.readI32();
              struct.setIdFuncionarioIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          default:
            org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
        }
        iprot.readFieldEnd();
      }
      iprot.readStructEnd();

      // check for required fields of primitive type, which can't be checked in the validate method
      struct.validate();
    }

    public void write(org.apache.thrift.protocol.TProtocol oprot, Reporte struct) throws org.apache.thrift.TException {
      struct.validate();

      oprot.writeStructBegin(STRUCT_DESC);
      if (struct.latitud != null) {
        oprot.writeFieldBegin(LATITUD_FIELD_DESC);
        oprot.writeString(struct.latitud);
        oprot.writeFieldEnd();
      }
      if (struct.longitud != null) {
        oprot.writeFieldBegin(LONGITUD_FIELD_DESC);
        oprot.writeString(struct.longitud);
        oprot.writeFieldEnd();
      }
      if (struct.nombreOtroConduc != null) {
        oprot.writeFieldBegin(NOMBRE_OTRO_CONDUC_FIELD_DESC);
        oprot.writeString(struct.nombreOtroConduc);
        oprot.writeFieldEnd();
      }
      oprot.writeFieldBegin(IDCONDUCTOR1_FIELD_DESC);
      oprot.writeI32(struct.idconductor1);
      oprot.writeFieldEnd();
      oprot.writeFieldBegin(FOLIO_UNICO_DICTAMEN_FIELD_DESC);
      oprot.writeI32(struct.folioUnico_dictamen);
      oprot.writeFieldEnd();
      oprot.writeFieldBegin(ID_FUNCIONARIO_FIELD_DESC);
      oprot.writeI32(struct.idFuncionario);
      oprot.writeFieldEnd();
      oprot.writeFieldStop();
      oprot.writeStructEnd();
    }

  }

  private static class ReporteTupleSchemeFactory implements org.apache.thrift.scheme.SchemeFactory {
    public ReporteTupleScheme getScheme() {
      return new ReporteTupleScheme();
    }
  }

  private static class ReporteTupleScheme extends org.apache.thrift.scheme.TupleScheme<Reporte> {

    @Override
    public void write(org.apache.thrift.protocol.TProtocol prot, Reporte struct) throws org.apache.thrift.TException {
      org.apache.thrift.protocol.TTupleProtocol oprot = (org.apache.thrift.protocol.TTupleProtocol) prot;
      java.util.BitSet optionals = new java.util.BitSet();
      if (struct.isSetLatitud()) {
        optionals.set(0);
      }
      if (struct.isSetLongitud()) {
        optionals.set(1);
      }
      if (struct.isSetNombreOtroConduc()) {
        optionals.set(2);
      }
      if (struct.isSetIdconductor1()) {
        optionals.set(3);
      }
      if (struct.isSetFolioUnico_dictamen()) {
        optionals.set(4);
      }
      if (struct.isSetIdFuncionario()) {
        optionals.set(5);
      }
      oprot.writeBitSet(optionals, 6);
      if (struct.isSetLatitud()) {
        oprot.writeString(struct.latitud);
      }
      if (struct.isSetLongitud()) {
        oprot.writeString(struct.longitud);
      }
      if (struct.isSetNombreOtroConduc()) {
        oprot.writeString(struct.nombreOtroConduc);
      }
      if (struct.isSetIdconductor1()) {
        oprot.writeI32(struct.idconductor1);
      }
      if (struct.isSetFolioUnico_dictamen()) {
        oprot.writeI32(struct.folioUnico_dictamen);
      }
      if (struct.isSetIdFuncionario()) {
        oprot.writeI32(struct.idFuncionario);
      }
    }

    @Override
    public void read(org.apache.thrift.protocol.TProtocol prot, Reporte struct) throws org.apache.thrift.TException {
      org.apache.thrift.protocol.TTupleProtocol iprot = (org.apache.thrift.protocol.TTupleProtocol) prot;
      java.util.BitSet incoming = iprot.readBitSet(6);
      if (incoming.get(0)) {
        struct.latitud = iprot.readString();
        struct.setLatitudIsSet(true);
      }
      if (incoming.get(1)) {
        struct.longitud = iprot.readString();
        struct.setLongitudIsSet(true);
      }
      if (incoming.get(2)) {
        struct.nombreOtroConduc = iprot.readString();
        struct.setNombreOtroConducIsSet(true);
      }
      if (incoming.get(3)) {
        struct.idconductor1 = iprot.readI32();
        struct.setIdconductor1IsSet(true);
      }
      if (incoming.get(4)) {
        struct.folioUnico_dictamen = iprot.readI32();
        struct.setFolioUnico_dictamenIsSet(true);
      }
      if (incoming.get(5)) {
        struct.idFuncionario = iprot.readI32();
        struct.setIdFuncionarioIsSet(true);
      }
    }
  }

  private static <S extends org.apache.thrift.scheme.IScheme> S scheme(org.apache.thrift.protocol.TProtocol proto) {
    return (org.apache.thrift.scheme.StandardScheme.class.equals(proto.getScheme()) ? STANDARD_SCHEME_FACTORY : TUPLE_SCHEME_FACTORY).getScheme();
  }
}

