/**
 * Autogenerated by Thrift Compiler (0.12.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#ifndef ApiFuncionario_CONSTANTS_H
#define ApiFuncionario_CONSTANTS_H

#include "ApiFuncionario_types.h"

namespace Thrift {

class ApiFuncionarioConstants {
 public:
  ApiFuncionarioConstants();

};

extern const ApiFuncionarioConstants g_ApiFuncionario_constants;

} // namespace

#endif
